blogs	CREATE TABLE `blogs` (
 `id` int(11) NOT NULL AUTO_INCREMENT,
 `titleEn` varchar(255) NOT NULL,
 `titleAr` varchar(255) NOT NULL,
 `slug` varchar(255) NOT NULL,
 `contentEn` longtext NOT NULL,
 `contentAr` longtext NOT NULL,
 `tagsEn` text DEFAULT NULL,
 `tagsAr` text DEFAULT NULL,
 `imageUrl` varchar(255) DEFAULT NULL,
 `readTime` int(11) DEFAULT NULL,
 `author` varchar(100) NOT NULL,
 `createdAt` datetime NOT NULL,
 `updatedAt` datetime(3) NOT NULL DEFAULT current_timestamp(3) ON UPDATE current_timestamp(3),
 `publishedAt` datetime(3) DEFAULT NULL,
 `excerptEn` text DEFAULT NULL,
 `excerptAr` text DEFAULT NULL,
 `metaTitleEn` varchar(191) DEFAULT NULL,
 `metaTitleAr` varchar(191) DEFAULT NULL,
 `metaDescriptionEn` text DEFAULT NULL,
 `metaDescriptionAr` text DEFAULT NULL,
 `status` enum('DRAFT','PUBLISHED','ARCHIVED') NOT NULL DEFAULT 'PUBLISHED',
 `featured` tinyint(1) NOT NULL DEFAULT 0,
 `views` int(11) NOT NULL DEFAULT 0,
 `authorEn` varchar(191) NOT NULL DEFAULT 'Merkwave Team',
 `authorAr` varchar(191) NOT NULL DEFAULT 'فريق ميرك ويف',
 PRIMARY KEY (`id`),
 KEY `idx_blogs_slug` (`slug`),
 KEY `idx_blogs_status` (`status`),
 KEY `idx_blogs_featured` (`featured`),
 KEY `idx_blogs_publishedAt` (`publishedAt`)
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
clients	CREATE TABLE `clients` (
 `id` int(11) NOT NULL AUTO_INCREMENT,
 `createdAt` datetime(3) NOT NULL DEFAULT current_timestamp(3),
 `updatedAt` datetime(3) NOT NULL DEFAULT current_timestamp(3) ON UPDATE current_timestamp(3),
 `slug` varchar(255) NOT NULL,
 `nameEn` varchar(255) NOT NULL,
 `nameAr` varchar(255) NOT NULL,
 `descriptionEn` text DEFAULT NULL,
 `descriptionAr` text DEFAULT NULL,
 `isActive` tinyint(1) NOT NULL DEFAULT 1,
 `logoUrl` varchar(255) DEFAULT NULL,
 `websiteUrl` varchar(191) DEFAULT NULL,
 `is_featured` tinyint(1) NOT NULL DEFAULT 0 COMMENT '1 = Featured, 0 = Not Featured',
 PRIMARY KEY (`id`),
 UNIQUE KEY `client_slug` (`slug`),
 KEY `idx_clients_slug` (`slug`),
 KEY `idx_clients_isActive` (`isActive`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
projects	CREATE TABLE `projects` (
 `id` int(11) NOT NULL AUTO_INCREMENT,
 `client_id` int(11) DEFAULT NULL,
 `slug` varchar(255) NOT NULL,
 `titleEn` varchar(255) NOT NULL,
 `titleAr` varchar(255) NOT NULL,
 `descriptionEn` text DEFAULT NULL,
 `descriptionAr` text DEFAULT NULL,
 `challenge_en` text DEFAULT NULL,
 `challenge_ar` text DEFAULT NULL,
 `solution_en` text DEFAULT NULL,
 `solution_ar` text DEFAULT NULL,
 `key_features_en` text DEFAULT NULL COMMENT 'JSON array of key features in English',
 `key_features_ar` text DEFAULT NULL COMMENT 'JSON array of key features in Arabic',
 `results_achieved_en` text DEFAULT NULL COMMENT 'JSON array of results in English',
 `results_achieved_ar` text DEFAULT NULL COMMENT 'JSON array of results in Arabic',
 `client_name` varchar(255) DEFAULT NULL,
 `project_date` date DEFAULT NULL,
 `technologiesEn` varchar(255) DEFAULT NULL,
 `technologiesAr` text DEFAULT NULL,
 `status` enum('DRAFT','IN_PROGRESS','COMPLETED','ARCHIVED') NOT NULL DEFAULT 'COMPLETED',
 `featured` tinyint(1) NOT NULL DEFAULT 0,
 `order` int(11) DEFAULT NULL,
 `gallery_images` text DEFAULT NULL COMMENT 'JSON array of image paths',
 `category` enum('WEB_DEVELOPMENT','MOBILE_DEVELOPMENT','DESKTOP_APPLICATION','DIGITAL_MARKETING','BRANDING','ECOMMERCE','SEO','SOCIAL_MEDIA','MEDIA_PRODUCTION','PHOTOGRAPHY') NOT NULL,
 `imageUrl` varchar(255) DEFAULT NULL,
 `demoUrl` varchar(255) DEFAULT NULL,
 `codeUrl` varchar(191) DEFAULT NULL,
 `accent_color` varchar(20) NOT NULL,
 `createdAt` timestamp NOT NULL DEFAULT current_timestamp(),
 `updatedAt` datetime(3) NOT NULL DEFAULT current_timestamp(3) ON UPDATE current_timestamp(3),
 PRIMARY KEY (`id`),
 UNIQUE KEY `project_slug` (`slug`),
 KEY `idx_projects_slug` (`slug`),
 KEY `idx_projects_clientId` (`client_id`),
 KEY `idx_projects_category` (`category`),
 KEY `idx_projects_status` (`status`),
 KEY `idx_projects_featured` (`featured`),
 CONSTRAINT `fk_client` FOREIGN KEY (`client_id`) REFERENCES `clients` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci